### ISSUE TITLE
How to display a list of blog entries?

### ISSUE THREAD

**Issue by t-kelly** [koistya/react-static-boilerplate#15]
Going through my list of must-haves. What will be the best way to show a list of pages in a given directory? i.e. Show a list of all blog entries on the `/blog/index.html` page.

My thinking is we could somehow include pages and some content in a state object. Thoughts? 

--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by koistya** [comment]
Yeap, that's a good idea! There is `tools/pages.js` script which reads all the files in the `src` folder except `js`, maybe we can use the output from this script as a state/context variable for the app..
