### ISSUE TITLE
'npm start' and 'npm run deploy' throwing error

### ISSUE THREAD

**Issue by miapoulos** [koistya/react-static-boilerplate#17]
Hey there!

I've downloaded the files and ran 'npm install', but when I run 'npm start' I get this error:
```
Child
             Asset   Size     Chunks                   Chunk Names
    app.node.js  32 kB              0   [emitted]  main
render
ReferenceError: npm is not defined
    at Object.<anonymous> (/Users/poulosm/Downloads/react-static-boilerplate-master/build/app.node.js:305:3)
```
I've also tried running 'npm run deploy' and get this error: 
```
deploy
clean
pages
TypeError: Can't call method on  undefined
    at TypeError (<anonymous>)
    at module.exports (/Users/poulosm/Downloads/react-static-boilerplate-master/node_modules/babel-core/node_modules/core-js/modules/$.defined.js:3:28)
```

--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by DocSavage** [comment]
Yes, the same issue happens for 'npm run build' after pages.

**Comment by SargoDarya** [comment]
Having the same issue and it seems to be not trivial to debug.

**Comment by SargoDarya** [comment]
Fixed the bug in the above commit.

**Comment by koistya** [comment]
I have refactored automation scripts, combined them into one - `run.js`. Try running `node run help` or `node run build` from a command line.
