### ISSUE TITLE
Integrate react-routing or react-router library

### ISSUE THREAD

**Issue by koistya** [koistya/react-static-boilerplate#24]
--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by dsernst** [comment]
Why?

**Comment by ianwalter** [comment]
+1 for react-router. This project is already using `history` and has a `Link` component that is similar to the one in react-router right?

**Comment by koistya** [comment]
I just have integrated [Universal Router](https://github.com/kriasoft/universal-router). Which has routes like:

```
{
  path: '/post/:id',
  async action({ params }) {
    const resp = await fetch(`/api/posts/${params.id}`);
    const data = await resp.json();
    return { title: data.title, component: Post, props: data };
  }
}
```

Which is a plain JavaScript object with `path` (`path-to-regexp` string or regexp), `action` (sync or async function), and optional `children` (array with child routes).

It can be easily converted to React Router if needed. For that, the `action()` method should be replaced with `getComponent()`, and tweak `core/app.js` a little.
