### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by trungdq88** [koistya/react-static-boilerplate#29]
How do I debug in Chrome DevTools? After `npm start` the code shown in Chrome DevTools is not readable.

<img width="244" alt="screenshot 2015-09-26 12 23 38" src="https://cloud.githubusercontent.com/assets/4214509/10115993/757cebb0-6449-11e5-8ec2-5655ae0de4aa.png">

It would be great if you can share a little bit about working with DevTool in `react-static-boilerplate` because I am falling in love with this.

**Comment by koistya** [comment]
![image](https://cloud.githubusercontent.com/assets/197134/10116077/1cf6ef66-642d-11e5-90bf-7c31ea022c8c.png)

You can play with different source map settings in `tools/config.js/devtool`
