### ISSUE TITLE
ReferenceError: global not defined

### ISSUE THREAD

**Issue by yagni** [koistya/react-static-boilerplate#31]
I'm trying to use three.js and so I added a `<script>` tag referencing a CDN version of it in my Html.js. However, I'm having trouble using the THREE global in my index.js page, like so (paraphrased, so sorry if there's a typo):
```javascript
export default class extends Component {
  constructor(props) {
    this.state({matrix: new THREE.Matrix3()});
  }

  render() {
    return (
      <div>
        <MyComponent matrix={this.state.matrix} />
      </div>
    );
  }
}
```

When the render task runs, it gives me a "ReferenceError: THREE is not defined" when running ReactDOM.renderToString for the index page. I'm guessing it's because this is happening before it pulls in the Html component further down in the task, during the ReactDOM.renderToStaticMarkup call.

Any ideas how I can solve this?

**Comment by koistya** [comment]
Do you want it to be rendered into HTML? If not, you can mount this component after the page was loaded in a browser. See `componentDidMount() { .. }`

**Comment by yagni** [comment]
Thanks for the quick reply! I found out three.js supports server-side rendering through their npm package named three, so I installed that and added an import statement at the top of my index.js and it seems to be working.
