### ISSUE TITLE
`static propTypes` causing Unexpected Token errors out of the box

### ISSUE THREAD

**Issue by cassidoo** [koistya/react-static-boilerplate#36]
After running `npm install` and `npm start`, there's multiple `Unexpected token` errors that look like this:

```
    Module build failed: SyntaxError: /Users/cassidoo/GitHub/hub/pages/500.js: Unexpected token (11:19)
       9 | export default class extends Component {
      10 |
    > 11 |   static propTypes = {
```

**Comment by koistya** [comment]
Do you have `.babelrc` file in the root of your project containing `{ "stage": 0 }`?

**Comment by cassidoo** [comment]
I don't, should that have been added on `npm install`?

**Comment by koistya** [comment]
I have refactored build automation scripts, combined them into one - `run.js`. Try running `node run help` or `node run build` from a command line (it requires Node.js v6).
