### ISSUE TITLE
Disable server side rendering step

### ISSUE THREAD

**Issue by dsernst** [koistya/react-static-boilerplate#45]
I'm having a bunch of trouble with `npm start` failing because I'm using `d3.csv` which depends on XHR, so the pre-render step throws this `ReferenceError: XMLHttpRequest is not defined`. I've tried a bunch of fixes but I'm no longer sure how much help the pre-rendering really offers, and ready to just give up on it.

What's the best way to disable the server side rendering step, and what are the implications?

**Comment by dsernst** [comment]
Still looking for an answer to this, but in case anyone else runs into similar problems I was able to improve development by wrapping the problematic components with:

```js
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

if (canUseDOM) {
  <ClientOnlyComponent />
}
```

like [in this example](https://github.com/koistya/react-static-boilerplate/blob/cc2da061a4b4424041f8652132f37c707fd0376c/app.js#L32).

**Comment by thejmazz** [comment]
Cheers @dsernst, had the same problem with [formsy-material-ui](https://github.com/mbrookes/formsy-material-ui). Wrapping the form in a `canUseDOM` allowed server render to finish.

**Comment by koistya** [comment]
The server-side rendering is now disabled by default.
