### ISSUE TITLE
Static pages not found when using trailing "/" in url?

### ISSUE THREAD

**Issue by jeberly** [koistya/react-static-boilerplate#46]
I thought this was an issue with my site at first, but it appears the demo is broken in the same manner. 

http://react-static.tarkus.me/about (works)

http://react-static.tarkus.me/about/ (does NOT work)

Was this intentional?  Is there a work around?  

FWIW, I am using s3 as a deploy endpoint and have my index doc name set to index.html

**Comment by koistya** [comment]
That's how GitHub Pages works, if you have `/about.html` file, you can open it in a browser either like `www.example.com/about.html` or `www.example.com/about` but not `www.example.com/about/`. With S3 it might make sense to generate `/about/index.html` instead.. You can play with it by modifying `tools/lib/routes-loader.js`.

**Comment by jeberly** [comment]
Thanks for response.  I had already moved to this pattern `/about/index.html`.  

This is how s3 handles this. http://stackoverflow.com/questions/30090254/aws-s3-forces-302-redirects-when-url-has-no-trailing-slash-need-301s

I do see a brief "flash" of correct content when I hit url with trailing slash, then it changes to "not found" page

It feels like react is triggering the "not found" after js loads.  I will take a look at `tools/lib/routes-loader.js`

**Comment by dvdplm** [comment]
I also ran into this today and found no better solution than hacking `tools/lib/routes-loader.js` to add duplicate routes when needed: `/foo/bar` and `/foo/bar/`.
That's fine I guess, but I wonder if there's a more elegant solution.

**Comment by bionikspoon** [comment]
@dvdplm instead of duplicating the routes, try adding this `if` statement:

```javascript
// # app.js
const route = async(path, callback) => {
  if (path.endsWith('/') && path !== '/') {
    path = path.slice(0, -1);
  }
  const handler = routes[path] || routes['/404'];
  const component = await handler();
  await callback(<App store={store}>{React.createElement(component)}</App>);
};
```

The keys in the `routes` object don't have slashes.  If you drop the slash you can use the key.  And in the browser if you try `example.com/about` it adds the slash (assuming `./pages/about/index.js` setup).

**Comment by n8sabes** [comment]
Please see #70 as this issue appears to be the same or related. I believe the bug is with `tools/lib/routes-loader.js` not correctly generating the default index.html function correctly if the sub-directory it's not included in `Navigation.js`.

**Comment by n8sabes** [comment]
Check out #70 as it appears including the sub-directory in `Navigation.js` fixes the 404 error. @bionikspoon, great workaround. I may not be understanding the underlying code well enough, but it seems like a bug in `tools/lib/routes-loader.js`.

**Comment by LDubya** [comment]
Looks like you can use query strings if you do it a certain way.

works:
/blog/?foo=bar 

doesn't work: 
/blog/index.html?foo=bar
/blog/index?foo=bar

surprisingly, this works:
//blog/index?foo=bar (notice the 2 slashes)

**Comment by LucaBlackDragon** [comment]
@bionikspoon adding the `if` statement you proposed above works for in-site navigation (ie. `<a className="Navigation-link" href="/about/" onClick={Link.handleClick}>About</a>` in Navigation.js), but if you try to load [http://localhost:3000/about/](http://localhost:3000/about/) directly you get a browser error (eg. a standard 404 error on MS Edge and a `Cannot GET /about/` on Chrome)

**Comment by iDVB** [comment]
@koistya How is it that this now works in the demo **with** and **without** slash?
What was the fix? 

I'm planning on using S3 and would really not want to have to deal with ugly index.html in the paths.
