### ISSUE TITLE
babel compatible 

### ISSUE THREAD

**Issue by creeperyang** [koistya/react-static-boilerplate#54]
Currently when I run `npm run clean` after `npm install`, got Error:

```bash
/Users/xx/soft/nvm/versions/node/v0.12.6/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
          ^
ReferenceError: [BABEL] [eval]: Unknown option: /Users/xx/work/projects/react-static-boilerplate/.babelrc.stage
...
```

It seems that it's an error with babel **incompatible**. The `babel-node` used the global installed `babel-cli@6.3.15`, and when I check local `node_modules/.bin/` , no `babel-node`.

Maybe it's **required** to tell user that globally installed `babel-cli@6.x` will crash tool script.  And any plan to support `babel@6.x`?

**Comment by koistya** [comment]
@creeperyang the project has been refactored to support Babel v6, it also now requires Node.js v6 to build and run the web app locally.
