### ISSUE TITLE
how to add client dependencies

### ISSUE THREAD

**Issue by mgenev** [koistya/react-static-boilerplate#56]
like let's say i wanted to add bootstrap or ratchet or google maps. How would I do that? 

seems like my assets have to end up in the `/build` folder, but where to prep them up so they end up there?

**Comment by koistya** [comment]
One way is to tweak `run.js => copy` script to copy required files into the `/build` folder. But it's always better to require files in your application source code and let Webpack to build the dependency tree and bundle your app including all the referenced static assets such as images and CSS.

Feel free to re-open if it's till an issue.
