### ISSUE TITLE
404 redirect not working 

### ISSUE THREAD

**Issue by JianGuo222** [koistya/react-static-boilerplate#65]
Hi, 

I'm trying to test 404 error redirect page, but seems browser sync server is not redircting 404 errors.

for example:
http://localhost:3000/xxx

it returns Cannot GET /xxx in the browser instead of redirecting to /404 page.

anyone know how to redirect?

thanks

**Comment by JianGuo222** [comment]
this is also related to wildcard routing issue. for example if I want to redirect /item/itemID to /Item page, how should I do that?

**Comment by JianGuo222** [comment]
to answer my own question, here is a solution for 404:
https://github.com/BrowserSync/browser-sync/blob/master/examples/404.js

not sure if there is any better solution

**Comment by JianGuo222** [comment]
also for wildcard routing, use this in browser-sync server
https://cnpmjs.org/package/http-proxy-middleware

**Comment by koistya** [comment]
With the recent version of RSB, you can add a wildcard route at the end of the list of routes:

const routes = [
  { path: '/', action() {/* render home page */} },
  { path: '/about', action() {/* render about page */} },
  { path: '/404', action() {/* render 404 page */} },
  { path: '*', action({ history }) { history.push('/404'); } },
}

**Comment by koistya** [comment]
The default behavior on many websites is to show error page right on the same URL, here is an example:

https://facebook.github.io/react/foo

But if this is not what you need, you can either configure redirects via hosting provider's admin panel (e.g. in Amazon S3 they have redirect rules for that). Or, alternatively, add this logic into `/pages/error/ErrorPage.js` React component.
