### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by tomasite** [koistya/react-static-boilerplate#66]
Hi, first thanks for your boilerplate!
I just have one problem when I try import react-youtube (https://github.com/troybetz/react-youtube). Note sure if it comes from the module itself or just a problem of configuration in my app but here is the stacktrace:
```
Starting 'render'...
ReferenceError: document is not defined
    at load ([..]/webapp/node_modules/load-script/index.js:3:14)
    at exports.default ([..]/webapp/node_modules/youtube-player/dist/es5/loadYouTubeIframeAPI.js:43:33)
    at Object.<anonymous> ([..]/webapp/node_modules/youtube-player/dist/es5/index.js:41:58)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([..]/webapp/node_modules/react-youtube/dist/YouTube.js:23:22)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
(I already tried to escape the serve side rendering with a canUseDom check but it changes nothing, the error occurs during the import..)

Thanks in advance for your help!
Thomas

**Comment by dsernst** [comment]
I see you opened a similar issue over in that module https://github.com/troybetz/react-youtube/issues/55. 

> (I already tried to escape the serve side rendering with a canUseDom check but it changes nothing, the error occurs during the import..)

Are you saying that simply adding `import 'react-youtube'` to the top of a file causes `npm start` to fail? Even if the component is never used?

**Comment by tomasite** [comment]
Thanks for your answer @dsernst!
I just checked and yes: even if the component is never used, the ```npm start``` fails because of the import.. This is why I also created an issue in the dedicated repo ;)

**Comment by koistya** [comment]
You may want to do conditional `require(...)` instead of `import`, for example:

```js
import React from 'react';
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

class VideoPlayer extends Component {
  state = { player: null };
  componentDidMount() {
    const YouTube = require('react-youtube');      // <--
    this.setState({ player: <YouTube /> });
  }
  render() {
    return (
      <div>
        </h1>Video Player</h1>
        {this.state.player}
      </div>
    );
  }
}

export default VideoPlayer;

**Comment by tomasite** [comment]
Hi @koistya, thanks for your answer! I tried your solution but even if there is no more error when I ```npm start``` the player doesn't load..
This time when I take a look at the js console, I find this error:
```
Unhandled promise rejection Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
I know this quite generic and not directly related to you boilerplate, sorry.
Here is a snippet of my code if you find something obvious:
```
import React, { Component } from 'react';

class VideoPlayer extends Component {
  state = { player: null };

  componentDidMount() {
    const YouTube = require('react-youtube');
    const opts = {
      height: '390',
      width: '640',
      playerVars: {
        autoplay: 1
      }
    };
    this.setState({ player: <YouTube videoId='2g811Eo7K8U' opts={opts} /> });
  }

  render() {
    return (
      <div>
        <h1>Video Player</h1>
        {this.state.player}
      </div>
    );
  }
}

export default VideoPlayer;

export default class extends Component {

  render() {
    return (
      <div>
        <VideoPlayer />
      </div>
    );
  }

}
```
Thanks again,
Thomas

**Comment by dsernst** [comment]
Do you need the double `export`?

**Comment by tomasite** [comment]
@dsernst no, indeed (but still have the error ;))

**Comment by dsernst** [comment]
If you add this `console.log`:

```js
  render() {
    console.log(this.state.player)
    return (
      <div>
        <h1>Video Player</h1>
        {this.state.player}
      </div>
    );
```

What does it print to the client console?

**Comment by tomasite** [comment]
as you see in the file attached it seems to be correctly instanciated ..
<img width="619" alt="object" src="https://cloud.githubusercontent.com/assets/725084/12536258/4f7c7b14-c2a0-11e5-98b8-cd682a048acf.png">

**Comment by dsernst** [comment]
Can you tell exactly which component is throwing the `Element type is invalid` error? E.g. putting `console.log`'s before and after or using `debugger` to step through.

**Comment by tomasite** [comment]
The error seems to come from ```es6.promise.js```
<img width="895" alt="error" src="https://cloud.githubusercontent.com/assets/725084/12536495/8131d896-c2a7-11e5-8ef4-e4fd95d71efc.png">

**Comment by dsernst** [comment]
I think es6.promise.js is evaluating one of the render functions. 

What does the console look like if you do this:

```js
import React, { Component } from 'react';

console.log('init VideoPlayer.js')

class VideoPlayer extends Component {
  state = { player: null };

  componentDidMount() {
    console.log('about to require("react-youtube")')
    const YouTube = require('react-youtube');
    const opts = {
      height: '390',
      width: '640',
      playerVars: {
        autoplay: 1
      }
    };
    this.setState({ player: <YouTube videoId='2g811Eo7K8U' opts={opts} /> });
    console.log('end of VideoPlayer componentDidMount')
  }

  render() {
    console.log('rendering VideoPlayer')
    console.log('this.state.player: ', this.state.player)
    return (
      <div>
        <h1>Video Player</h1>
        {this.state.player}
      </div>
    );
  }
}

export VideoPlayer;

console.log('initializing wrapper component')

export default class extends Component {

  render() {
    console.log('rendering exported wrapper component')
    return (
      <div>
        <VideoPlayer />
      </div>
    );
  }

}
```

**Comment by dsernst** [comment]
Actually I wonder if the `player: null` is creating a problem, based on that first warning in your console. What if you had this instead:

```js
class VideoPlayer extends Component {
  state = { player: <div></div> };

  componentDidMount() {
...
```

**Comment by tomasite** [comment]
<img width="684" alt="log" src="https://cloud.githubusercontent.com/assets/725084/12539036/d1c200a0-c2e9-11e5-9e69-6a1c8b833f98.png">
@dsernst I tried your code (with your last suggestion too) but still not working :(
(I saw that @gajus marked the issue as a bug, maybe he has an idea about that?)

**Comment by dsernst** [comment]
Hmm. It really seems like a problem with `react-youtube`. The fact that it's throwing the warnings as soon as it's initialized, and doesn't load at all, even in a standard client-side environment, suggests `react-static-boilerplate` isn't causing the trouble.

Have you tried rendering it with this same configuration in another clean application?

**Comment by tjallingt** [comment]
Hey @dsernst and @tomasite, 

>I see you opened a similar issue over in that module troybetz/react-youtube#55. Not sure if I agree with the author's sentiment that it's not related to react-youtube. It seems like that component doesn't support server-side rendering.

First of all I'm not the author, just a lowly collaborator :smile: 
Secondly its maybe more accurate to say that server side rendering is something that `react-youtube` can't support because of the YouTube API dependency (unless I'm missing something you can't load that api server side).
Although I do agree that we should create a fall-back so server side will render to a `<div>` or whatever as not to break any applications that do use server-side rendering.
I have no experience working with server side rendering of react components and I'm not even sure if we can make it behave differently when rendered server side without nasty consequences... (so any pointers here would be much appreciated).

> Hmm. It really seems like a problem with react-youtube. The fact that it's throwing the warnings as soon as it's initialized, and doesn't load at all, even in a standard client-side environment, suggests react-static-boilerplate isn't causing the trouble.

As I understand, this has been fixed by the change in [youtube-player#3](https://github.com/gajus/youtube-player/issues/3)

**Comment by tomasite** [comment]
Hello @tjallingt, thanks for your answer.
Indeed the warning has been fixed in the youtube-player which is great but I still have a problem during the server side rendering. If you have any clue on how to fix this it would be awesome!

**Comment by tjallingt** [comment]
That's great! Like I said it would definitely be desirable to not have the component break when rendered server side. Although I'm not sure just rendering a `<div>` server-side will work, its worth a try haha.
I am going to create a new issue and pull request for this issue so I think this one can be closed :lock:

**Comment by koistya** [comment]
I think this issue should not be relevant anymore with the latest version of RSB. Feel free to reopen.
