### ISSUE TITLE
using react-font-awesome  in webpack config

### ISSUE THREAD

**Issue by awongCM** [koistya/react-static-boilerplate#71]
I'm trying to using this font-awesome css icons from this github repo.

https://github.com/andreypopp/react-fa

Despite its instructions to use, I'm not entirely sure it's applicable for this static boilerplate I'll be using since the boilerplate comes preconfigured with the css loaders already.

Thus I'm just curious to know how to configure webpack config to import font-awesome?  I'm not familiar with webpack environment setup btw vs gulp/grunt.

**Comment by koistya** [comment]
The simplest solution is just add the following line to `components/Html/Html.js`:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
```

Then you can use those icons in React components as described in FontAwesome tutorial:

```html
<i className="fa fa-camera-retro fa-5x />
```

**Comment by awongCM** [comment]
Great! Will try that out.
