### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zwhitchcox** [koistya/react-static-boilerplate#73]
I see that you are using a 404.html so you don't have to create every directory with an index.html page, which is genius, but won't that send a 404 status with the page? If not, how did you avoid that?

**Comment by koistya** [comment]
This `404.html` files is GitHub Pages convention, when there is no a file on disk corresponding to the requested URL, GitHub pages sends status code 404 and the contents of this `404.html` file. For all existing pages, there should be a generated `index.html` or `<path>.html` page that are generated for you when you run `npm run build` before deployment.

**Comment by zwhitchcox** [comment]
Oh, sorry, my mistake. I had no idea you could create an `about.html` page and not have to include the `.html` in the url. In fact, in the jekyll docs, it says you have to generate a directory with the page name you want and then put an index.html file in it. http://jekyllrb.com/docs/pages/#named-folders-containing-index-html-files

Well that's another eye opener!

**Comment by koistya** [comment]
That is also something specific to GitHub Pages. In Amazon S3, for example, you need to change the pattern to generate `index.html` in its own folder, e.g. `/about.html` should become `/about/index.html`. I think this should be easy to tweak.
