### ISSUE TITLE
.JSX extension not supported in the pages directory on the server-side render

### ISSUE THREAD

**Issue by ncksllvn** [koistya/react-static-boilerplate#75]
The corresponding HTML files are not generated for files with the `.jsx` extension in the pages directory. PR #74 fixes this.

**Comment by ncksllvn** [comment]
VS Code requires JSX files to use the JSX extension rather than JS if you want all of the benefits of the editor so I went about updating the extensions when I noticed this.

**Comment by koistya** [comment]
The static pages are now generated based on the list of routes in `routes.json`, so having `.jsx` extension should not be a problem.
