### ISSUE TITLE
Migrating to babel-cli

### ISSUE THREAD

**Issue by zwhitchcox** [koistya/react-static-boilerplate#76]
In the the npm script requires babel-cli, not babel for the new version of babel. And if we upgrade this, we're also going to have to update the .babelrc. Also, the `require` statement will not work for exported functions, so we'll either have to import those functions, add `.default` to the end of them, or add `module.exports` to the end of every file. I have already done this in my project and could make a pull request if people were interested in doing that. Is there any interest? If so, do we want to use `import`, `default`, or `module.exports`? I personally used `.default`, but it doesn't make any difference to me, except in some cases where you have to use a particular method.

**Comment by koistya** [comment]
@zwhitchcox I just refactored the code inside the `tools` folder to be compatible with Node.js 6 that supports almost all the ES2015 features and beyond (except Harmony Modules). So you can run these scripts directly, without Babel: `node tools/build.js`, `node tools/build.js --release` etc.

**Comment by zwhitchcox** [comment]
Cool thanks!
