### ISSUE TITLE
Why is this callback asynchronous

### ISSUE THREAD

**Issue by zwhitchcox** [koistya/react-static-boilerplate#80]
Been going through the code base, and I'm pretty new to ES'16 (Aren't we all), and I dont' understand why [this callback](https://github.com/koistya/react-static-boilerplate/blob/master/app.js#L25) would be asynchronous when it doesn't return a promise?

**Comment by zwhitchcox** [comment]
I just tested it and verified that it does work even when not asynchronous.

**Comment by koistya** [comment]
Take a look at `fetch()` method (that comes natively in Chrome). It is an asynchronous method. You can either execute it as a regular function (without waiting for a response):

```js
// just execute, and don't worry about what it retuns, it will execute in "background"
fetch('http://swapi.co/api/people/1');
```

or, you can execute it and wait for the response:

```js
fetch('http://swapi.co/api/people/1').then(x => x.text()).then(x => console.log(x));
```

You can also run it inside another `async` function, if so, you don't need to use `.then()` (old school):

```
async function test() {
  const resp = await fetch('http://swapi.co/api/people/1');
  const text = await resp.text();
  console.log(text);
}
```

**Comment by zwhitchcox** [comment]
Yeah, I figured that stuff out, by looking at your other project, `react-starter-kit`. Very cool stuff! Will contribute more once I have more disposable income haha. I've learned a lot from these projects. Keep up the good work!
