### ISSUE TITLE
not working after NCU

### ISSUE THREAD

**Issue by crivera** [koistya/react-static-boilerplate#82]
Hi

i did a NCU and now the project is not starting anymore

can you fix this

**Comment by koistya** [comment]
@crivera what's NCU, what error message do you see?

**Comment by crivera** [comment]
i used npm-check-updates to get all the latest versions of the dependencies... 

https://www.npmjs.com/package/npm-check-updates

but after running it i get some babel errors etc

**Comment by deakster** [comment]
Yea, the main reason seems to be the changes in babel 6, it's a major version upgrade with plenty of breaking changes from babel 5 (babel-cli, presets etc).

**Comment by koistya** [comment]
All the project dependencies have been updated to the most recent versions (Babel 6, React Hot Loader 3 etc.)
