### ISSUE TITLE
Editing routes

### ISSUE THREAD

**Issue by Christilut** [koistya/react-static-boilerplate#84]
I changed the pages structure a bit (which works fine) but I am also trying to edit the routes based on a configuration file. So what I want is that `/about` points to `/about/_default.js`  (the reason is that I am editing these routes so it could point to `/about/en_EN.js` or `/about/mydomain.com`, depending on the used configuration) .
The routes look like this after they are loaded:
```js
[ { path: '/404/_default', file: '404/_default.js' },
  { path: '/404/de_DE', file: '404/de_DE.js' },
  { path: '/about', file: 'about/_default.js' },
  { path: '/about/de_DE', file: 'about/de_DE.js' },
  { path: '/index', file: 'index.js' },
  { path: '/', file: 'index/_default.js' },
  { path: '/index/de_DE', file: 'index/de_DE.js' },
  { path: '/index/de', file: 'index/de.js' } ]
```
But on the `/about` page I get "Cannot GET /about". The path `/about/de_DE` works fine.
The `/` path also doesn't work, seems like the same issue.

What am I missing here?

Edit: updated `/` path, I said it worked earlier but actually doesn't

**Comment by koistya** [comment]
@Christilut can you please try this approach with the latest version of RSB:

```
const routes = {
  path: '/',
  children: [
    { path: '/about', action() { ... } },
    { path: '/about/de_DE', action() { .. } },
  ],
};
```

Where action must return an object having at least `title` (string) and `component` (React) fields.

**Comment by Christilut** [comment]
Thanks, with the new router its much easier to accomplish :)
