### ISSUE TITLE
react-router

### ISSUE THREAD

**Issue by t-kelly** [koistya/react-static-boilerplate#9]
I'm having issues with routing on this boilerplate. Is their any reason you chose not to go with React Router? @jxnblk seems to be pull it off here: https://github.com/jxnblk/react-static-site-boilerplate

--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by TeeKz** [comment]
Actually I see you've been working on your own router, react-routing. What about integrating that into this project?

**Comment by koistya** [comment]
Yep, definitely! I'm still thinking what's the best way to improve the routing (e.g. `/users/:id`) and navigation (e.g. `Location.goBack()`, `Location.naivgateTo(path, {replace: true})`) in this project.

**Comment by TeeKz** [comment]
I've just finished integrating your react-routing package into this, you can find it here: https://github.com/TeeKz/react-static-boilerplate/tree/react-routing

I like how you automatically make the routes, but it makes the project folder pretty messy compared to your react-starter-kit project. What if we had routes created automatically for 'content' made with jade files (like RSK) and then manually code in other routes?

**Comment by koistya** [comment]
@TeeKz I was going to support both JSX and Markdown or Jade formats, so you could choose what format to use for each particular page. For example:

```
/pages/index.md
/pages/products.md
/pages/cart/index.js (JSX)
/pages/cart/checkout.js (JSX)
```

**Comment by TeeKz** [comment]
@koistya So every page will need a md/js/jade file? Yeah that could work!

Build the site directory structure based on the `/pages` internal structure and then we could easily have the other folders you use in RSK, such as `/components`, `utils`, etc. to keep things modular and tidy.

**Comment by koistya** [comment]
Yep

**Comment by TeeKz** [comment]
Can we use what I've done so far with react-routing? I still need to adjust the automated route creation to work for the different formatting, but other then that things are working nicely!

Let me know :)

**Comment by koistya** [comment]
Yep, looks good. I would just mix it with automatic route generation for static pages.

**Comment by Elesant** [comment]
@TeeKz is there a way to know which link in the navigation is active?

**Comment by TeeKz** [comment]
Haven't got there yet! We'll have to start managing state to get that.

**Comment by Elesant** [comment]
@TeeKz Haha I see. Awesome work so far! Need this so badly :p

**Comment by oompt** [comment]
I'm interested to see how the this turns out. 

That said, I might try integrating Rakt Router if anyone has any interest.
