### ISSUE TITLE
React static boilerplate compiled content?

### ISSUE THREAD

**Issue by dardub** [koistya/react-static-boilerplate#92]
Hi,

I just cloned the latest version and I see a lot of good changes. But I ran a release build and looked at the source and don't see any content in the generated index.html. How are we to handle seo appropriately? This was the entire reason I used this boilerplate.

**Comment by noradaiko** [comment]
+1,

Generated code also doesn't include html of sub pages, so the server responds 404 when I reload at sub page deployed on GitHub pages.

**Comment by koistya** [comment]
I had to temporarily disable this feature that generates static `.html` pages, but it shouldn't be hard to bring it back, will do that later.

**Comment by noradaiko** [comment]
glad to hear that!
It would be even nice if you add a version tag for each release so that we can use older(stable) version for avoiding regressions due to new major update. I believe conforming to semver might be good.
Thanks for great boilerplate!

**Comment by koistya** [comment]
@noradaiko the way it's currently works is that all HTTP requests should be redirected to `index.html` page on the server (this should be easy to configure in Amazon S3, Firebase Hosting, and in case with GitHub Pages you can copy `index.html` and save it as `404.html` which is a workaround to make the site work in GitHub Pages for now).

**Comment by noradaiko** [comment]
@koistya Thanks for giving the workaround, but in the way using `404.html` the status code is always `404` on GitHub Pages so it'd be not good for SEO and HTTP rules.
I'm using old version of this boilerplate for now, will try it when supporting generating html files again!

**Comment by frenzzy** [comment]
Alternatively you can use the [react-starter-kit](https://github.com/kriasoft/react-starter-kit) with a very similar product structure and export your application as static files, see: https://github.com/kriasoft/react-starter-kit/pull/642

**Comment by noradaiko** [comment]
@frenzzy wow, sounds nice. I'll take a look!

**Comment by v3yr0n** [comment]
@koistya Thanks for this boilerplate! I was using an older version too, and now i only get the one html file (index) when i ran the release build too. Any idea on when can we have the "old" functionality again? :)

**Comment by koistya** [comment]
@v3yr0n Create `tools/render.js` script that should generate a list of URLs from `routes/index.js` file. Then iterate over that list and generate a static markup. The `core/main.js` can export `render(path)` method that the renderer can use to generate that static markup.

**Comment by v3yr0n** [comment]
Where's the core/main.js file? You mean app.js? :)

**Comment by v3yr0n** [comment]
Trying to create the render script. Not sure if i'm in the right path. I'm using the resolve from the universal router to render the page and output the result as html so i can write it to a file. It works well if i don't use the require.ensure function in the theroute page. But if i use it i get: "TypeError: require.ensure is not a function\n    at theroute.js:15:15\n    at new Promise".
I'm using babel-node to run the render script. 

`import { resolve } from 'universal-router';

task('render', new Promise((theres, reject) => {
   resolve(routes.children, { path: '/theroute' }).then((result) => {
      console.log(result);
    });
  })
);`

Any help?
Thanks!

**Comment by v3yr0n** [comment]
Hi! 

I'm sorry for asking again, but can you give me some advice on this? 

Thanks!

**Comment by koistya** [comment]
@v3yr0n a few more steps:
- In `webpack.config.js` copy the config: `const nodeConfig = extend(true, {}, config)`; modify config.output.file to something like `build/[name].node.js`; set `nodeConfig.target` to "node", set "limit chunks" to 1 (so that no chunks are created with that Node.js bundle); export it alonside with regular client-side bundle config, e.g. module.exports = [clientConfig, nodeConfig]. Add export default { render(path) { ... } }; method to `core/main.js`.

This way, when you bundle the site, the build folder will contain regular client-side bundle `build/main.js` and one more bundle that you can use for generating static pages `build/main.node.js`. Then in your `tools/render.js` script you can import that bundle `const bundle = require('./build/main.node.js')`, and call `bundle.render('/theroute')` method that returns HTML markup.

**Comment by v3yr0n** [comment]
Thanks, i'll do that and let you know if it works. 
I don't have any `core/main.js` file... you are referring to the `core` folder on the project root, right?

**Comment by koistya** [comment]
@v3yr0n ah, right `core/app.js`

**Comment by v3yr0n** [comment]
This is harder that what i thought :) 
I'm getting this warning:
`[emit[BABEL] Note: The code generator has deoptimised the styling of "/build/main.node.js" as it exceeds the max of "100KB".`

And after that this error:
`Error: only one instance of babel-polyfill is allowed`

This happens when i add the `const bundle = require('../build/main.node.js');` to the render.js file.
Any idea?

Also, not sure about the export in the core/app.js. Can you send some code please? 

Thanks!

**Comment by v3yr0n** [comment]
Also, i'm running the script with babel-node. I'm using it because otherwise i can't use import. It should work same way, right? or should i change it to node?

**Comment by v3yr0n** [comment]
So removing the `import 'babel-polyfill';` from core/app.js solves that error. (is it needed?)
I added a function to the core/app.js file to be exported: 
    const routessss = async (path) => {
        console.log("routessss");
    };
and then
`export default {routessss};`

In the render.js file i have: 
    const { routessss } = require('../build/app.node');
    console.log("routessss",routessss);
but that console.log returns routessss undefined...

What am i doing wrong?

Thanks!

**Comment by v3yr0n** [comment]
Any update? 
Thanks!

**Comment by koistya** [comment]
@dardub @noradaiko @v3yr0n I just replaced imperative style routes with declarative (see [`routes.json`](https://github.com/koistya/react-static-boilerplate/blob/49a67f0/routes.json). These routes are parsed and compiled into JavaScript code with Webpack by using [`tools/webpack.routes-loader.js`](https://github.com/koistya/react-static-boilerplate/blob/49a67f0/tools/webpack.routes-loader.js) and [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp). At run time, when you call `router.resolve(routes, { path })` the router loads corresponding React component alongside with required data and returns it to the caller that itself calls `ReactDOM.render(component, container)` (see [`main.js#L41-46`](https://github.com/koistya/react-static-boilerplate/blob/49a67f0/main.js#L41-L46) and [`core/router.js`](https://github.com/koistya/react-static-boilerplate/blob/49a67f0/core/router.js)).

With these type of routes it should be extremely easy to add one more build step (see `tools/build.js`) that will go through the list of paths defined in `routes.json` and generate a corresponding `.html` page. If you want to take a stub on it that would be awesome!

**Comment by koistya** [comment]
`npm run build` now generates a static `.html` page for each route (see `tools/copy.js`). Feel free to reopen if this logic needs to be improved.

**Comment by noradaiko** [comment]
Cheers!🎉

**Comment by koistya** [comment]
@noradaiko BTW, what routing approach do you personally prefer, declarative or imperative? A poll :)

**Comment by noradaiko** [comment]
@koistya I prefer imperative way because it's explicit & easy to tweak👌

**Comment by v3yr0n** [comment]
@koistya what happened to this build script in the last commits? :) it's not in the run.js file...

**Comment by koistya** [comment]
@v3yr0n I'm not sure if it's worth the added complexity to pre-render HTML pages since Google can crawl dynamically generated sites just fine. Check out this article:

http://chrisarasin.com/react-seo/

Do you still need that feature?

**Comment by v3yr0n** [comment]
Yeah, i believe that SEO is not a problem :) I need to export the pages as static html because i want to maximize the compatibility between browsers. I need to embrace the maximum browsers I can, like the safari for ipad 1 :)

**Comment by v3yr0n** [comment]
But I was just asking, i can simply get your code from the 9a820de2b371348fe23f7e4639e17f6428afdca0 commit :)

**Comment by koistya** [comment]
@v3yr0n there are also multiple approach for generating static .html pages, I'd like to try this approach where you generate an HTML page by using some headless browser (as opposed to making your app work isomorphically in order to be able to pre-render it).

**Comment by tony2nite** [comment]
I think SEO is still a bit of a problem. Sure Google is OK, but even the article above highlights 20-30% of traffic might not be from Google. Also there can be issues with social sharing as well e.g. Facebook's OpenGraph parser and Twitter as well don't render JS, so the page you share through that won't show the right titles, metadata, preview images etc if that is only generated by JS, unless here is actual HTML sitting at that endpoint.

Be interesting to look at other options for this.
